// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 sol pbc

/**
 * The Cloudflare Worker entrypoint for `trust.solstone.app`. Read-only:
 * this Worker holds no signing key, no publisher credential, and cannot
 * write evidence. It renders a portal model built and verified offline
 * (`make build-model`) and embedded at deploy time — it never re-fetches
 * or re-verifies evidence itself, and it never proxies a raw evidence URL.
 *
 * The generated stylesheet and sitemap routes are served from `handle()`/
 * `buildSitemap()` (neither has a file on disk — both are produced from the
 * embedded model). The static files this surface serves as-is (the vendored
 * brand font, `robots.txt`) are delegated to the Workers Static Assets
 * binding instead of embedded in this bundle.
 */

import { ASSET_HEADERS, HTML_HEADERS } from "./src/legacy/response-policy";
import { handle } from "./src/portal";
import { buildSitemap } from "./src/portal/sitemap";
import { STYLESHEET_PATH } from "./src/portal/routes";
// Generated by `make build-model` immediately before every deploy; never
// committed (see .gitignore) and never hand-edited (type supplied by the
// ambient declaration in `model.generated.d.ts`, since the file itself need
// not exist yet for `tsc --noEmit` to check this module). A stale or
// missing file fails the bundle loudly at deploy time rather than shipping
// an out-of-date register silently.
import model from "./model.generated.json";
import type { PortalModelResult } from "./src/legacy/types";

const result = model as PortalModelResult;

interface Env {
	ASSETS: { fetch(request: Request): Promise<Response> };
}

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		const url = new URL(request.url);
		if (url.pathname === "/sitemap.xml") {
			const headers = new Headers(HTML_HEADERS);
			headers.set("Content-Type", "application/xml; charset=utf-8");
			return new Response(buildSitemap(result), { status: 200, headers });
		}
		if (
			url.pathname === "/robots.txt" ||
			(url.pathname !== STYLESHEET_PATH && url.pathname.startsWith("/static/"))
		) {
			const assetRes = await env.ASSETS.fetch(request);
			// Every ASSET_HEADERS value except Content-Type: a real static file's
			// own auto-detected media type (e.g. font/woff2) is correct and must
			// not be overwritten by the CSS-specific value this policy also names.
			const headers = new Headers(assetRes.headers);
			for (const [k, v] of Object.entries(ASSET_HEADERS)) {
				if (k === "Content-Type") continue;
				headers.set(k, v);
			}
			return new Response(assetRes.body, {
				status: assetRes.status,
				headers,
			});
		}
		const res = handle(url.pathname, result);
		return new Response(res.body, {
			status: res.status,
			headers: res.headers,
		});
	},
};
