// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 sol pbc

/**
 * The Cloudflare Worker entrypoint for `trust.solstone.app`. Read-only:
 * this Worker holds no signing key, no publisher credential, and cannot
 * write evidence. It renders a portal model built and verified offline
 * (`make build-model`) and embedded at deploy time — it never re-fetches
 * or re-verifies evidence itself, and it never proxies a raw evidence URL.
 */

import { handle } from "./src/portal";
// Generated by `make build-model` immediately before every deploy; never
// committed (see .gitignore) and never hand-edited (type supplied by the
// ambient declaration in `model.generated.d.ts`, since the file itself need
// not exist yet for `tsc --noEmit` to check this module). A stale or
// missing file fails the bundle loudly at deploy time rather than shipping
// an out-of-date register silently.
import model from "./model.generated.json";
import type { PortalModelResult } from "./src/legacy/types";

const result = model as PortalModelResult;

export default {
	fetch(request: Request): Response {
		const url = new URL(request.url);
		const res = handle(url.pathname, result);
		return new Response(res.body, {
			status: res.status,
			headers: res.headers,
		});
	},
};
